image: node:10.19.0

pipelines:
  branches:
    lesson-5/staging:
      - step:
          name: Copy staging environment to .env.json
          script:
            - cp src/env/.env.staging.json src/env/.env.json
          artifacts:
            - src/env/.env.json            
      - step:
          name: A REAL build process!
          caches:
            - node
          script:
            - npm install
            - export npm_config_public_url=https://chrisfrew.in/skillshare-typescript-staging
            - npm run build
            - tar -zcf node_modules.tar.gz node_modules/
          artifacts:
            - build/**
            - node_modules.tar.gz
            - index.js
            - .foreverignore
      - step:
          name: Deploy build folder to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/skillshare-typescript-staging/build'
                LOCAL_PATH: 'build/*'
      - step:
          name: Deploy env file to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/skillshare-typescript-staging/src/env'
                LOCAL_PATH: 'src/env/.env.json'
      - step:
          name: Deploy node_modules.tar.gz tarball to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/skillshare-typescript-staging'
                LOCAL_PATH: 'node_modules.tar.gz'
      - step:
          name: Deploy index.js file to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/skillshare-typescript-staging'
                LOCAL_PATH: 'index.js'
      - step:
          name: Deploy .foreverignore file to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/skillshare-typescript-staging'
                LOCAL_PATH: '.foreverignore'
      - step:
          name: Unpack tarball via SSH
          script:
            - ssh $USER@$SERVER 'cd /var/www/skillshare-typescript-staging && tar -zxf node_modules.tar.gz'
    lesson-5/master:
      - step:
          name: Copy master environment to .env.json
          script:
            - cp src/env/.env.master.json src/env/.env.json
          artifacts:
            - src/env/.env.json
      - step:
          name: A REAL build process!
          caches:
            - node
          script:
            - npm install
            - export npm_config_public_url=https://chrisfrew.in/skillshare-typescript-master
            - npm run build
            - tar -zcf node_modules.tar.gz node_modules/
          artifacts:
            - build/**
            - node_modules.tar.gz
            - index.js
            - .foreverignore
      - step:
          name: Deploy build folder to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/skillshare-typescript-master/build'
                LOCAL_PATH: 'build/*'
      - step:
          name: Deploy env file to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/skillshare-typescript-master/src/env'
                LOCAL_PATH: 'src/env/.env.json'
      - step:
          name: Deploy node_modules.tar.gz tarball to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/skillshare-typescript-master'
                LOCAL_PATH: 'node_modules.tar.gz'
      - step:
          name: Deploy index.js file to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/skillshare-typescript-master'
                LOCAL_PATH: 'index.js'
      - step:
          name: Deploy .foreverignore file to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/skillshare-typescript-master'
                LOCAL_PATH: '.foreverignore'
      - step:
          name: Unpack tarball via SSH
          script:
            - ssh $USER@$SERVER 'cd /var/www/skillshare-typescript-master && tar -zxf node_modules.tar.gz'
